### ISSUE TITLE
update to actix 3

### ISSUE THREAD

**Issue by tronta** [Igosuki/actix-web-metrics-mw#16]
I'm using actix3 for a project. Therefore it would be great if the dependency could be bumped up.
What do you think?
Would you be interested in a PR? I'm not a pro, but I could try to provide one.

**Comment by Igosuki** [comment]
It's done already, look at the master branch.

**Comment by Igosuki** [comment]
If you want to use it at your company we could look into improving the crate otherwise it should be fine as is.
